sudo: required
language: generic
services:
- docker
cache:
  ccache: true
  cargo: true
  directories:
  - "$HOME/.conan/data"
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc48-rust-nightly DOCKER_IMAGE=imazen/build_if_gcc48
      RUST_CHANNEL=nightly UPLOAD_BUILD=True JOB_NAME="build_if_gcc48_rust_nightly" RUST_BACKTRACE=1
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc54-rust-nightly DOCKER_IMAGE=imazen/build_if_gcc54
      RUST_CHANNEL=nightly UPLOAD_BUILD=True JOB_NAME="build_if_gcc54_rust_nightly" RUST_BACKTRACE=1
    sudo: required
    services:
    - docker
  - os: osx
    osx_image: xcode7.3
    env: PACKAGE_SUFFIX=x86_64-apple-darwin-xcode73-rust-nightly  TARGET=x86_64-apple-darwin
      RUST_CHANNEL=nightly UPLOAD_BUILD=True JOB_NAME="xcode73" RUST_BACKTRACE=1
    language: rust
    rust: nightly
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc49-rust-nightly DOCKER_IMAGE=imazen/build_if_gcc49
      RUST_CHANNEL=nightly UPLOAD_BUILD=True JOB_NAME="build_if_gcc49_rust_nightly" RUST_BACKTRACE=1
    sudo: required
    services:
    - docker
  - os: linux
    dist: trusty
    env: PACKAGE_SUFFIX=x86_64-linux-gcc54-rust-nightly DOCKER_IMAGE=imazen/build_if_gcc54
      RUST_CHANNEL=nightly UPLOAD_BUILD=False COVERAGE=True VALGRIND=True JOB_NAME="build_if_gcc54_rust_nightly_coverage_valgrind" RUST_BACKTRACE=1
    sudo: required
    services:
    - docker
install:
- ci/travis_install.sh
script:
- ci/travis_run.sh
deploy:
  provider: s3
  access_key_id: AKIAIMZ7QOL24GUASH6A
  secret_access_key:
    secure: izS5sgSOhDwjuQaFTTgMlhUd5759ZnuoxxoFDo41XZATNw58P6FtzdfslfoVa+xXjq/1N0GDAM+ENm7XYNITVqq1aJARYKy5X+IUwVKQw/UYx0rb1X2ZV7oDHsFvY5pSRiVFD1tQ0fZ9JKAkb1LTnSutfVYHNYvPHiyYQf07nig=
  bucket: imageflow-nightlies
  acl: public_read
  skip_cleanup: true
  local_dir: artifacts/upload
  on:
    repo: imazen/imageflow
